export Home from './home'
export NoMatch from './no-match'
export Login from './login'
export Signup from './signup'
export ForgotPassword from './forgot-password'
export OtherPage from './other-page'
export Strategies from './strategies'
export Strategy from './strategy'